import type { OutputToken } from './assemble.ts';
import { type Mode, MODES } from './constants.ts';

const NOTICE = 'Generated by @dnd-mapp/design-tokens from the D&D Mapp Figma library. Do not edit.';
const HEADER = `/* ${NOTICE} */`;

/**
 * Creates the stylesheet that declares every token as a custom property on `:root`.
 *
 * It sets `color-scheme` to follow the system. A `light-dark()` value resolves where the property is used, so setting
 * `color-scheme` on any element switches the colors of that element and its children.
 */
export function createCss(tokens: OutputToken[]): string {
    // A blank line goes before each top-level group, such as `color` or `spacing`.
    const declarations = tokens.flatMap((token, index) => [
        ...(token.path[0] === tokens[index - 1]?.path[0] ? [] : ['']),
        `    ${token.name}: ${token.value};`,
    ]);

    return [HEADER, ':root {', '    color-scheme: light dark;', ...declarations, '}', ''].join('\n');
}

/** A tree of token groups, with the tokens as leaves. */
interface TokenTree {
    [name: string]: TokenTree | OutputToken;
}

/** How the members of an object or a map are written, for each output. */
interface MemberFormat {
    key(name: string): string;
    openGroup(key: string): string;
    closeGroup: string;
    token(key: string, token: OutputToken): string[];
}

function buildTree(tokens: OutputToken[]): TokenTree {
    const root: TokenTree = {};

    for (const token of tokens) {
        let node = root;

        for (const group of token.path.slice(0, -1)) {
            node = (node[group] ??= {}) as TokenTree;
        }
        node[token.path.at(-1)!] = token;
    }
    return root;
}

function formatMembers(tokens: OutputToken[], format: MemberFormat): string[] {
    const leaves = new Set<unknown>(tokens);

    const formatTree = (tree: TokenTree, indent: string): string[] =>
        Object.entries(tree).flatMap(([name, node]) => {
            const key = format.key(name);

            if (leaves.has(node)) {
                return format.token(key, node as OutputToken).map((line) => `${indent}${line}`);
            }
            return [
                `${indent}${format.openGroup(key)}`,
                ...formatTree(node as TokenTree, `${indent}    `),
                `${indent}${format.closeGroup}`,
            ];
        });

    return formatTree(buildTree(tokens), '    ');
}

/** Writes a string as a single-quoted literal, which JavaScript, TypeScript, and Sass all read the same way. */
function quote(value: string): string {
    return `'${value.replaceAll('\\', '\\\\').replaceAll("'", "\\'")}'`;
}

function formatJsKey(name: string): string {
    return /^[A-Za-z_$][\w$]*$/.test(name) ? name : quote(name);
}

function reference(token: OutputToken): string {
    return quote(`var(${token.name})`);
}

/**
 * Returns the CSS value of a token without `var()` references, which the stylesheet uses for the parts of a text style.
 * Only colors differ between the modes, so any other token has the same value in every mode.
 */
function resolvedValue(token: OutputToken): string {
    return token.type === 'color' ? token.value : token.modeValues[MODES[0]];
}

/**
 * Formats the value of a token for the `values` object. A color has a value for each mode, even when the modes share
 * it, so every color has the same shape.
 */
function formatJsValue(token: OutputToken, format: (mode: Mode, value: string) => string, separator: string): string {
    if (token.type !== 'color') {
        return quote(resolvedValue(token));
    }
    return `{ ${MODES.map((mode) => format(mode, quote(token.modeValues[mode]))).join(separator)} }`;
}

/**
 * Creates the module that exports two frozen objects: `tokens`, with a `var()` reference for every token, and
 * `values`, with the CSS value of every token.
 */
export function createJs(tokens: OutputToken[]): string {
    const references = formatMembers(tokens, {
        key: formatJsKey,
        openGroup: (key) => `${key}: Object.freeze({`,
        closeGroup: '}),',
        token: (key, token) => [`${key}: ${reference(token)},`],
    });
    const values = formatMembers(tokens, {
        key: formatJsKey,
        openGroup: (key) => `${key}: Object.freeze({`,
        closeGroup: '}),',
        token: (key, token) => {
            const value = formatJsValue(token, (mode, value) => `${mode}: ${value}`, ', ');

            return [`${key}: ${token.type === 'color' ? `Object.freeze(${value})` : value},`];
        },
    });

    return [
        HEADER,
        'export const tokens = Object.freeze({',
        ...references,
        '});',
        '',
        'export const values = Object.freeze({',
        ...values,
        '});',
        '',
    ].join('\n');
}

/** Documents a token with its description and, when given, its CSS value, so editors show both on hover. */
function formatDoc(prefix: string, token: OutputToken, value?: string): string[] {
    const text = [token.description, value && `\`${value}\``].filter(Boolean).join(' ');

    return text ? [`${prefix} ${text}`] : [];
}

function formatJsDoc(token: OutputToken, value?: string): string[] {
    return formatDoc('/**', token, value).map((line) => `${line.replaceAll('*/', '*\\/')} */`);
}

/** Creates the declarations of the module, with every reference and value as a literal type. */
export function createDts(tokens: OutputToken[]): string {
    const references = formatMembers(tokens, {
        key: formatJsKey,
        openGroup: (key) => `readonly ${key}: {`,
        closeGroup: '};',
        token: (key, token) => [...formatJsDoc(token, resolvedValue(token)), `readonly ${key}: ${reference(token)};`],
    });
    const values = formatMembers(tokens, {
        key: formatJsKey,
        openGroup: (key) => `readonly ${key}: {`,
        closeGroup: '};',
        token: (key, token) => [
            ...formatJsDoc(token),
            `readonly ${key}: ${formatJsValue(token, (mode, value) => `readonly ${mode}: ${value}`, '; ')};`,
        ],
    });

    return [
        HEADER,
        'export declare const tokens: {',
        ...references,
        '};',
        '',
        'export declare const values: {',
        ...values,
        '};',
        '',
    ].join('\n');
}

/** Keeps a whole number as a number key, so `map.get($tokens, 'spacing', 16)` finds it, and quotes any other key. */
function formatScssKey(name: string): string {
    return /^\d+$/.test(name) ? name : quote(name);
}

function scssVariable(token: OutputToken): string {
    return `$${token.path.join('-')}`;
}

function formatScssValue(token: OutputToken): string {
    if (token.type === 'color') {
        return `(${MODES.map((mode) => `${quote(mode)}: ${token.modeValues[mode]}`).join(', ')})`;
    }
    const value = resolvedValue(token);

    // A font stack is a comma-separated list, so it needs parentheses inside a map.
    return token.type === 'fontFamily' || token.type === 'typography' ? `(${value})` : value;
}

/**
 * Creates the Sass module. It declares a variable with the `var()` reference of every token, the `$tokens` map of
 * those references, and the `$values` map with the value of every token as a Sass value.
 *
 * The module emits no CSS, so it can be loaded with `@use` from any number of stylesheets.
 */
export function createScss(tokens: OutputToken[]): string {
    const variables = tokens.flatMap((token, index) => [
        ...(token.path[0] === tokens[index - 1]?.path[0] ? [] : ['']),
        ...formatDoc('///', token, resolvedValue(token)),
        `${scssVariable(token)}: var(${token.name});`,
    ]);
    const map = (token: (key: string, token: OutputToken) => string[]): string[] =>
        formatMembers(tokens, { key: formatScssKey, openGroup: (key) => `${key}: (`, closeGroup: '),', token });

    return [
        `// ${NOTICE}`,
        ...variables,
        '',
        '/// The `var()` reference of every token, in the groups of the `tokens` object.',
        '$tokens: (',
        ...map((key, token) => [`${key}: ${scssVariable(token)},`]),
        ');',
        '',
        '/// The value of every token. A color has a value for each mode.',
        '$values: (',
        ...map((key, token) => [`${key}: ${formatScssValue(token)},`]),
        ');',
        '',
    ].join('\n');
}

/**
 * Creates a DTCG token file with the tokens of a mode. The aliases are resolved, and every token has its own `$type`,
 * so the file stands on its own.
 */
export function createTokensJson(tokens: OutputToken[], mode: Mode): string {
    const root: Record<string, unknown> = {};

    for (const token of tokens) {
        let node = root;

        for (const group of token.path.slice(0, -1)) {
            node = (node[group] ??= {}) as Record<string, unknown>;
        }
        node[token.path.at(-1)!] = {
            $type: token.type,
            $value: token.resolvedValues[mode],
            $description: token.description,
            $extensions: token.extensions,
        };
    }
    // `JSON.stringify` leaves out the members that are `undefined`, such as a missing description.
    return `${JSON.stringify(root, null, 4)}\n`;
}
