import { compileString } from 'sass';
import { describe, expect, it } from 'vitest';
import type { OutputToken } from './assemble.ts';
import { createCss, createDts, createJs, createScss, createTokensJson } from './outputs.ts';

const HEADER = '/* Generated by @dnd-mapp/design-tokens from the D&D Mapp Figma library. Do not edit. */';

function srgb(hex: string, component: number) {
    return { colorSpace: 'srgb', components: [component, component, component], hex };
}

function same<T>(value: T) {
    return { light: value, dark: value };
}

const fontFamily: OutputToken = {
    path: ['font-family', 'mono'],
    type: 'fontFamily',
    name: '--dma-font-family-mono',
    value: '"JetBrains Mono", monospace',
    modeValues: same('"JetBrains Mono", monospace'),
    resolvedValues: same(['JetBrains Mono', 'monospace']),
    description: undefined,
    extensions: undefined,
};

const tokens: OutputToken[] = [
    {
        path: ['color', 'text', 'default'],
        type: 'color',
        name: '--dma-color-text-default',
        value: 'light-dark(#000000, #ffffff)',
        modeValues: { light: '#000000', dark: '#ffffff' },
        resolvedValues: { light: srgb('#000000', 0), dark: srgb('#ffffff', 1) },
        description: undefined,
        extensions: undefined,
    },
    {
        path: ['color', 'text', 'muted'],
        type: 'color',
        name: '--dma-color-text-muted',
        value: '#808080',
        modeValues: same('#808080'),
        resolvedValues: same(srgb('#808080', 0.5)),
        description: undefined,
        extensions: undefined,
    },
    fontFamily,
    {
        path: ['spacing', '16'],
        type: 'dimension',
        name: '--dma-spacing-16',
        value: '1rem',
        modeValues: same('1rem'),
        resolvedValues: same({ value: 1, unit: 'rem' }),
        description: '1rem (16px) in code.',
        extensions: { 'com.figma': { scopes: ['GAP'] } },
    },
];

describe('createCss', () => {
    it('should declare every token on the root, with a blank line before each group', () => {
        expect(createCss(tokens)).toBe(
            [
                HEADER,
                ':root {',
                '    color-scheme: light dark;',
                '',
                '    --dma-color-text-default: light-dark(#000000, #ffffff);',
                '    --dma-color-text-muted: #808080;',
                '',
                '    --dma-font-family-mono: "JetBrains Mono", monospace;',
                '',
                '    --dma-spacing-16: 1rem;',
                '}',
                '',
            ].join('\n'),
        );
    });
});

describe('createJs', () => {
    it('should export a frozen tree of var() references and a frozen tree of values', () => {
        expect(createJs(tokens)).toBe(
            [
                HEADER,
                'export const tokens = Object.freeze({',
                '    color: Object.freeze({',
                '        text: Object.freeze({',
                "            default: 'var(--dma-color-text-default)',",
                "            muted: 'var(--dma-color-text-muted)',",
                '        }),',
                '    }),',
                "    'font-family': Object.freeze({",
                "        mono: 'var(--dma-font-family-mono)',",
                '    }),',
                '    spacing: Object.freeze({',
                "        '16': 'var(--dma-spacing-16)',",
                '    }),',
                '});',
                '',
                'export const values = Object.freeze({',
                '    color: Object.freeze({',
                '        text: Object.freeze({',
                "            default: Object.freeze({ light: '#000000', dark: '#ffffff' }),",
                "            muted: Object.freeze({ light: '#808080', dark: '#808080' }),",
                '        }),',
                '    }),',
                "    'font-family': Object.freeze({",
                `        mono: '"JetBrains Mono", monospace',`,
                '    }),',
                '    spacing: Object.freeze({',
                "        '16': '1rem',",
                '    }),',
                '});',
                '',
            ].join('\n'),
        );
    });

    it('should escape quotes and backslashes in a value', () => {
        const value = `"D'Arcy\\", serif`;

        expect(createJs([{ ...fontFamily, value, modeValues: same(value) }])).toContain(
            `mono: '"D\\'Arcy\\\\", serif',`,
        );
    });
});

describe('createDts', () => {
    it('should declare both trees with literal types, documented with the description and the value', () => {
        expect(createDts(tokens)).toBe(
            [
                HEADER,
                'export declare const tokens: {',
                '    readonly color: {',
                '        readonly text: {',
                '            /** `light-dark(#000000, #ffffff)` */',
                "            readonly default: 'var(--dma-color-text-default)';",
                '            /** `#808080` */',
                "            readonly muted: 'var(--dma-color-text-muted)';",
                '        };',
                '    };',
                "    readonly 'font-family': {",
                '        /** `"JetBrains Mono", monospace` */',
                "        readonly mono: 'var(--dma-font-family-mono)';",
                '    };',
                '    readonly spacing: {',
                '        /** 1rem (16px) in code. `1rem` */',
                "        readonly '16': 'var(--dma-spacing-16)';",
                '    };',
                '};',
                '',
                'export declare const values: {',
                '    readonly color: {',
                '        readonly text: {',
                "            readonly default: { readonly light: '#000000'; readonly dark: '#ffffff' };",
                "            readonly muted: { readonly light: '#808080'; readonly dark: '#808080' };",
                '        };',
                '    };',
                "    readonly 'font-family': {",
                `        readonly mono: '"JetBrains Mono", monospace';`,
                '    };',
                '    readonly spacing: {',
                '        /** 1rem (16px) in code. */',
                "        readonly '16': '1rem';",
                '    };',
                '};',
                '',
            ].join('\n'),
        );
    });

    it('should escape the end of a comment in a description', () => {
        expect(createDts([{ ...fontFamily, description: 'Ends */ early.' }])).toContain('/** Ends *\\/ early.');
    });
});

describe('createScss', () => {
    it('should declare a variable for every token, and the maps of references and values', () => {
        expect(createScss(tokens)).toBe(
            [
                '// Generated by @dnd-mapp/design-tokens from the D&D Mapp Figma library. Do not edit.',
                '',
                '/// `light-dark(#000000, #ffffff)`',
                '$color-text-default: var(--dma-color-text-default);',
                '/// `#808080`',
                '$color-text-muted: var(--dma-color-text-muted);',
                '',
                '/// `"JetBrains Mono", monospace`',
                '$font-family-mono: var(--dma-font-family-mono);',
                '',
                '/// 1rem (16px) in code. `1rem`',
                '$spacing-16: var(--dma-spacing-16);',
                '',
                '/// The `var()` reference of every token, in the groups of the `tokens` object.',
                '$tokens: (',
                "    'color': (",
                "        'text': (",
                "            'default': $color-text-default,",
                "            'muted': $color-text-muted,",
                '        ),',
                '    ),',
                "    'font-family': (",
                "        'mono': $font-family-mono,",
                '    ),',
                "    'spacing': (",
                '        16: $spacing-16,',
                '    ),',
                ');',
                '',
                '/// The value of every token. A color has a value for each mode.',
                '$values: (',
                "    'color': (",
                "        'text': (",
                "            'default': ('light': #000000, 'dark': #ffffff),",
                "            'muted': ('light': #808080, 'dark': #808080),",
                '        ),',
                '    ),',
                "    'font-family': (",
                `        'mono': ("JetBrains Mono", monospace),`,
                '    ),',
                "    'spacing': (",
                '        16: 1rem,',
                '    ),',
                ');',
                '',
            ].join('\n'),
        );
    });

    it('should compile to a module that emits no CSS, and whose variables and maps Sass can use', () => {
        const compile = (source: string) =>
            compileString(source, {
                importers: [
                    {
                        canonicalize: (url) => (url === 'tokens' ? new URL('memory:tokens') : null),
                        load: () => ({ contents: createScss(tokens), syntax: 'scss' }),
                    },
                ],
            }).css;

        expect(compile("@use 'tokens';")).toBe('');
        expect(
            compile(`
                @use 'sass:map';
                @use 'tokens';

                .card {
                    color: tokens.$color-text-default;
                    padding: map.get(tokens.$tokens, 'spacing', 16);
                    margin: map.get(tokens.$values, 'spacing', 16) * 2;
                    background: map.get(tokens.$values, 'color', 'text', 'default', 'dark');
                    font-family: map.get(tokens.$values, 'font-family', 'mono');
                }
            `),
        ).toBe(
            [
                '.card {',
                '  color: var(--dma-color-text-default);',
                '  padding: var(--dma-spacing-16);',
                '  margin: 2rem;',
                '  background: #ffffff;',
                '  font-family: "JetBrains Mono", monospace;',
                '}',
            ].join('\n'),
        );
    });
});

describe('createTokensJson', () => {
    it('should write the tokens of a mode as DTCG, with a type on every token', () => {
        const json = createTokensJson(tokens, 'dark');

        expect(json).toMatch(/^\{\n {4}"color": \{\n/);
        expect(json).toMatch(/\n\}\n$/);
        expect(JSON.parse(json)).toEqual({
            'color': {
                text: {
                    default: { $type: 'color', $value: srgb('#ffffff', 1) },
                    muted: { $type: 'color', $value: srgb('#808080', 0.5) },
                },
            },
            'font-family': { mono: { $type: 'fontFamily', $value: ['JetBrains Mono', 'monospace'] } },
            'spacing': {
                16: {
                    $type: 'dimension',
                    $value: { value: 1, unit: 'rem' },
                    $description: '1rem (16px) in code.',
                    $extensions: { 'com.figma': { scopes: ['GAP'] } },
                },
            },
        });
    });

    it('should take the value of the given mode', () => {
        const [text] = tokens;

        expect(JSON.parse(createTokensJson([text!], 'light'))).toEqual({
            color: { text: { default: { $type: 'color', $value: srgb('#000000', 0) } } },
        });
    });
});
